### ISSUE TITLE
App is crashing!

### ISSUE THREAD

**Issue by yasirtahir** [alhazmy13/MediaRecorderDialog#2]
App is crashing while calling the MediaRecorderDialog. The reason of crashing is apparently the non-inflation of FloatingActionButton. But I am unable to find, as everything is fine. The library is there, it is linked as well. Can you figure out the root cause of this issue?

Here is the crash log:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mowe.complain/net.alhazmy13.gota.GotaActivity}: android.view.InflateException: Binary XML file line #50: Error inflating class android.support.design.widget.FloatingActionButton
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2689)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2754)
                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:145)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5938)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by alhazmy13** [comment]
Dear,, 

Above exception it's appears from your code not from MediaRecorderDialog, Can you please send to me the full log?

**Comment by yasirtahir** [comment]
I already fixed that issue. It was error regarding the inflating of FloatingActionButton in SoundDialog. It wasn't in my code

**Comment by trikiano** [comment]
same problem yasir .need help please what's the solution for that issue

**Comment by yasirtahir** [comment]
Try creating your own custom layout. 

Download the library, add this as module in your existing application then write your own layout.
